development:
  adapter: postgresql
  encoding: unicode
  database: ruby-rails-sample_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ruby-rails-sample_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ruby-rails-sample_production
  pool: 5