default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
adapter: postgresql
host: localhost
database: iris_development

production:
adapter: postgresql
host: localhost
database: iris_production

# test:
#   <<: *default
#   database: iris_test

# production:
#   <<: *default
#   database: iris_production
#   username: iris
#   password: <%= ENV['IRIS_DATABASE_PASSWORD'] %>
