development:
  adapter: postgresql
  encoding: unicode
  database: iris_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: iris_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: iris_production
  pool: 5